server:
  port: 9913

spring:
  application:
    name: hmily-account

#--------------- datasource  -----------
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmily_account?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
#------------- nacos discovery -----------
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#--------------------- logging --------------
logging:
  level:
    root: info
    com:
      xiaocai:
        distran: info
    org:
      dromara:
        hmily: info
    io:
      netty: info

mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Ribbon的负载均衡策略
ribbon:
  NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer : 0
  MaxAutoRetries: 0
  ReadTimeout: 3000

feign:
  hystrix:
    enabled : false
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能



